from __future__ import annotations

import os
from pathlib import Path

try:
    from dotenv import load_dotenv
except Exception:  # pragma: no cover - optional dependency

    def load_dotenv(*args, **kwargs):
        return False


BASE_DIR = Path(__file__).resolve().parent
for candidate in (
    BASE_DIR / ".env.local",
    BASE_DIR / ".env",
):
    if candidate.exists():
        load_dotenv(dotenv_path=candidate, override=True)
        break


MYSQL_CONFIG = {
    "host": os.getenv("MYSQL_HOST"),
    "user": os.getenv("MYSQL_USER"),
    "password": os.getenv("MYSQL_PASSWORD"),
    "database": os.getenv("MYSQL_DATABASE"),
    "raise_on_warnings": True,
}

ADDRESSFORGE_PROJECT_NAME = os.getenv("ADDRESSFORGE_PROJECT_NAME", "AddressForge")
ADDRESSFORGE_PORT = int(os.getenv("ADDRESSFORGE_PORT", "8010"))
ADDRESSFORGE_CONSOLE_PORT = int(os.getenv("ADDRESSFORGE_CONSOLE_PORT", "8011"))

ADDRESSFORGE_DEFAULT_PROFILE = os.getenv("ADDRESSFORGE_DEFAULT_PROFILE", "base_canada")
ADDRESSFORGE_MODEL_VERSION = os.getenv("ADDRESSFORGE_MODEL_VERSION", "canada_default_v1")
ADDRESSFORGE_REFERENCE_VERSION = os.getenv("ADDRESSFORGE_REFERENCE_VERSION", "reference_current")
ADDRESSFORGE_DATABASE = os.getenv("ADDRESSFORGE_DATABASE", os.getenv("MYSQL_DATABASE", "addressforge"))

ADDRESSFORGE_INGESTION_MODE = os.getenv("ADDRESSFORGE_INGESTION_MODE", "api")
ADDRESSFORGE_INGESTION_SOURCE_NAME = os.getenv("ADDRESSFORGE_INGESTION_SOURCE_NAME", "third_party")
ADDRESSFORGE_INGESTION_API_URL = os.getenv("ADDRESSFORGE_INGESTION_API_URL", "")
ADDRESSFORGE_INGESTION_API_TOKEN = os.getenv("ADDRESSFORGE_INGESTION_API_TOKEN", "")
ADDRESSFORGE_INGESTION_API_TIMEOUT = int(os.getenv("ADDRESSFORGE_INGESTION_API_TIMEOUT", "30"))
ADDRESSFORGE_INGESTION_API_BATCH_SIZE = int(os.getenv("ADDRESSFORGE_INGESTION_API_BATCH_SIZE", "1000"))

ADDRESSFORGE_INGESTION_DB_HOST = os.getenv("ADDRESSFORGE_INGESTION_DB_HOST", os.getenv("MYSQL_HOST", ""))
ADDRESSFORGE_INGESTION_DB_USER = os.getenv("ADDRESSFORGE_INGESTION_DB_USER", os.getenv("MYSQL_USER", ""))
ADDRESSFORGE_INGESTION_DB_PASSWORD = os.getenv("ADDRESSFORGE_INGESTION_DB_PASSWORD", os.getenv("MYSQL_PASSWORD", ""))
ADDRESSFORGE_INGESTION_DB_NAME = os.getenv("ADDRESSFORGE_INGESTION_DB_NAME", os.getenv("MYSQL_DATABASE", ""))
ADDRESSFORGE_INGESTION_DB_TABLE = os.getenv("ADDRESSFORGE_INGESTION_DB_TABLE", "source_raw_address")
ADDRESSFORGE_INGESTION_DB_CURSOR_COLUMN = os.getenv("ADDRESSFORGE_INGESTION_DB_CURSOR_COLUMN", "updated_at")
ADDRESSFORGE_INGESTION_DB_EXTERNAL_ID_COLUMN = os.getenv("ADDRESSFORGE_INGESTION_DB_EXTERNAL_ID_COLUMN", "external_id")
ADDRESSFORGE_INGESTION_DB_RAW_ADDRESS_COLUMN = os.getenv("ADDRESSFORGE_INGESTION_DB_RAW_ADDRESS_COLUMN", "raw_address_text")
ADDRESSFORGE_INGESTION_DB_CITY_COLUMN = os.getenv("ADDRESSFORGE_INGESTION_DB_CITY_COLUMN", "city")
ADDRESSFORGE_INGESTION_DB_PROVINCE_COLUMN = os.getenv("ADDRESSFORGE_INGESTION_DB_PROVINCE_COLUMN", "province")
ADDRESSFORGE_INGESTION_DB_POSTAL_CODE_COLUMN = os.getenv("ADDRESSFORGE_INGESTION_DB_POSTAL_CODE_COLUMN", "postal_code")
ADDRESSFORGE_INGESTION_DB_LATITUDE_COLUMN = os.getenv("ADDRESSFORGE_INGESTION_DB_LATITUDE_COLUMN", "latitude")
ADDRESSFORGE_INGESTION_DB_LONGITUDE_COLUMN = os.getenv("ADDRESSFORGE_INGESTION_DB_LONGITUDE_COLUMN", "longitude")
ADDRESSFORGE_INGESTION_DB_BATCH_SIZE = int(os.getenv("ADDRESSFORGE_INGESTION_DB_BATCH_SIZE", "1000"))

ADDRESSFORGE_INGESTION_CURSOR_TYPE = os.getenv("ADDRESSFORGE_INGESTION_CURSOR_TYPE", "updated_at")
ADDRESSFORGE_DEFAULT_LOOKBACK_SECONDS = int(os.getenv("ADDRESSFORGE_DEFAULT_LOOKBACK_SECONDS", "604800"))
ADDRESSFORGE_GPS_CONFLICT_METERS = float(os.getenv("ADDRESSFORGE_GPS_CONFLICT_METERS", "250"))

# Backward-compatible aliases for existing helper functions
ADDRESS_V2_DATABASE = ADDRESSFORGE_DATABASE
ADDRESS_V2_DEFAULT_LOOKBACK_SECONDS = ADDRESSFORGE_DEFAULT_LOOKBACK_SECONDS
ADDRESS_V2_GPS_CONFLICT_METERS = ADDRESSFORGE_GPS_CONFLICT_METERS

SALT = os.getenv("SALT", "")

LOG_FILE = os.getenv("ADDRESSFORGE_LOG_FILE", "runtime/addressforge.log")
INVALID_ROWS_FILE = os.getenv("ADDRESSFORGE_INVALID_ROWS_FILE", "runtime/invalid_rows.csv")

NS_GPS_BOUNDS = {
    "lat_min": 43.5,
    "lat_max": 47.0,
    "lon_min": -66.0,
    "lon_max": -60.0,
}

POSTAL_CODE_PATTERN = r"^[A-Z]\d[A-Z]\s*\d[A-Z]\d$"
